// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Building and Deploying your own application
Duration: 15:00

You will receive the information about the zip file containing the files of the aloha application. Please contact one of the instructors if you didn't receive this information.

Once you have unpacked the zip file containing the aloha application, switch to the application's folder and run a Maven build:

[source, bash, subs="normal,attributes"]
----
$ *cd aloha*
$ *mvn clean package*
----

Now that we created the local artifact, let's configure OpenShift to deploy our new artifact as an OpenShift application.

First we create a new build configuration in OpenShift:

[source, bash, subs="normal,attributes"]
----
$ *oc new-build --binary --name=aloha --allow-missing-images*
* A Docker build using binary input will be created
  * The resulting image will be pushed to image stream "aloha:latest"
  * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label build=aloha ...
imagestream "aloha" created
buildconfig "aloha" created
--> Success
----

Then we will tell OpenShift to start a new build from current folder. It will send all the contents of the content folder to the OpenShift daemon so it can create a new container image for us:

[source, bash, subs="normal,attributes"]
----
$ *oc new-build --binary --name=aloha --allow-missing-images*
* A Docker build using binary input will be created
  * The resulting image will be pushed to image stream "aloha:latest"
  * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label build=aloha ...
imagestream "aloha" created
buildconfig "aloha" created
--> Success
----
