// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Setup environment
Duration: 15:00

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Bring Your Own Laptop) style hands-on-lab.

### Hardware

- Operating System: Windows 7 (SP1), Mac OS X (10.8 or later), Fedora (21 or later)

### Software

#### Development tools

Make sure to have the following tools/packages installed:

- GIT
- Maven
- OpenShift CLI (oc)

### Accessing the RBC Workshop OpenShift cluster

You should have received a paper containing your username, password, and project for this workshop. Please let one of instructors know if you didn't receive the paper.

With the provided information, you can login in the cluster with the following command:

[source, bash, subs="normal,attributes"]
----
$ *oc login https://openshift-master.g2.rbcexpo.com/*
Username: yanaga
Password:
Login successful.

You have one project on this server: "yanaga"

Using project "yanaga".
----
